### ISSUE TITLE
Calling functions without parameters causes error

### ISSUE THREAD

**Issue by Coding-Cactus** [dsoon/PS2#4]
```
FUNCTION abc() RETURNS INTEGER
  RETURN 2
ENDFUNCTION

OUTPUT abc()
```

=> `[line 5] Syntax error: expression list missing an expression`

For reference:
```
FUNCTION abc(a : INTEGER) RETURNS INTEGER
  RETURN a + 2
ENDFUNCTION

OUTPUT abc(2)
```
Works without error.

**Comment by dsoon** [comment]
Added code change on expression.py line 151 to treat functions that take no arguments as simple variables, e.g.
FUNCTION abc RETURNS INTEGER
    RETURN 42
ENDFUNCTION

OUTPUT abc

1> 42
