### ISSUE TITLE
Functions that return BOOLEAN can not be used as a flag

### ISSUE THREAD

**Issue by hugomarfani** [dsoon/PS2#6]
When using a function which returns boolean as a flag the interpreter returns an error saying that there is a missing argument.

Actual Behaviour:

> NB isFull() returns boolean value

```
IF isFull() THEN
    RETURN FALSE
```
Returns error:
`Syntax error: missing expression`

Expected Behaviour:

> The code should act as if it was written out like it is below.

```
IF isFull() = TRUE THEN
    RETURN FALSE
```

This bug was found using the latest version of the PS2 interpreter.

**Comment by hugomarfani** [comment]
## UPDATE

This error persists when the code below is used:
```
IF isFull() = TRUE THEN
    RETURN FALSE
```
OR
```
IF isFull() == TRUE THEN
    RETURN FALSE
```

**Comment by hugomarfani** [comment]
Not an issue.

Calling functions with no parameters should be done using no brackets e.g.

```
IF isFull THEN
    RETURN FALSE
```

**Comment by dsoon** [comment]
That's correct. The '(' and the ')' are only used when arguments are passed to a function, or a procedure and not required otherwise. For a procedure it would look like this:
``DECLARE PROCEDURE SAY_HELLO
    OUTPUT "Hello"
ENDPROCEDURE

CALL SAY_HELLO
```
